### PR TITLE
Adjust HEBO to `FloatDistribution` with `step`

### PR DESCRIPTION
**Pull request by nabenabe0928**
This PR adjusts `HEBOSampler` so that it can handle `FloatDistribution` with `step` properly.

> [!NOTE]
> Originally, `HEBOSampler` falls back to `sample_independent` if there are any parameters with `FloatDistribution` and `step`.

Please use the following objective function for the verification!

```python
def objective(trial: optuna.Trial) -> float:
    trial.suggest_float("f", -5, 5)
    trial.suggest_float("f-log", 1, 100, log=True)
    trial.suggest_float("f-step", -2, 7, step=0.5)
    trial.suggest_float("f-step-non-divisable", 2, 7, step=3)
    trial.suggest_int("i", -5, 5)
    trial.suggest_int("i-log", 1, 100, log=True)
    trial.suggest_int("i-step", -2, 6, step=2)
    trial.suggest_int("i-step-non-divisable", 2, 7, step=3)
    trial.suggest_categorical("c", ["a", "b", "c"])
    print(trial.params)
    return trial.number
```

### CODE REVIEW

**Comment by nabenabe0928** [comment]
@y0z 
Could you check this PR?

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Comment by HideakiImamura** [comment]
@nabenabe0928 Could you resolve the conflict?

**Comment by nabenabe0928** [comment]
I noticed that I need to transform before `hebo.observe` as well.

**Comment by nabenabe0928** [comment]
I fixed so that HEBO now knows the exact indices for each parameter.

**Pull request merged**
