### PR TITLE
Directly import built-in features

### PR DESCRIPTION
**Pull request by HideakiImamura**
## Contributor Agreements

Please read the [contributor agreements](https://github.com/optuna/optunahub-registry/blob/main/CONTRIBUTING.md#contributor-agreements) and if you agree, please click the checkbox below.

- [x] I agree to the contributor agreements.

## Motivation

All built-in features should be directly used from optuna. This PR reduces unnecessary modules.

### CODE REVIEW

**Comment by HideakiImamura** [comment]
@not522 Could you review this PR?

**Comment by HideakiImamura** [comment]
This PR is ready for review.

**Comment by HideakiImamura** [comment]
@y0z Could you review this PR?

**Review by y0z — APPROVED** [review]
LGTM

**Pull request merged**
