### PR TITLE
[Proposal] Add seed argument to SimpleBaseSampler

### PR DESCRIPTION
**Pull request by y0z**
## Contributor Agreements

Please read the [contributor agreements](https://github.com/optuna/optunahub-registry/blob/main/CONTRIBUTING.md#contributor-agreements) and if you agree, please click the checkbox below.

- [x] I agree to the contributor agreements.

## Motivation

I received feedback from a contributor: " How do I set the random seed for independent sampling in `SimpleBaseSampler`? It is required to make my sampler reproducible." Researchers value reproducibility, so I want to support functionality to set `seed` to `SimpleBaseSampler`.

I think this change possibly needs discussion. If you have any other ideas, please let me know.

## Description of the changes

- Add a `seed` argument and make the seed work properly.

### CODE REVIEW

**Comment by y0z** [comment]
@toshihikoyanase Could you review this PR?

**Comment by toshihikoyanase** [comment]
@y0z Thank you for your proposal. The change looks reasonable.

> I think this change possibly needs discussion. If you have any other ideas, please let me know.

Could you please share some discussion points?
One discussion point may be an increase in complexity. I think it is acceptable since the `seed` argument has a default value, and users can still use the samplers without any arguments.

**Comment by y0z** [comment]
@toshihikoyanase 

> Could you please share some discussion points?

One of my ideas is introducing the `independent_sampler` argument with `RandomSampler()` as the default value rather than `seed`. This would allow users to employ an arbitrary sampler for independent sampling. How do you feel about this?

```python
class SimpleBaseSampler(BaseSampler, abc.ABC):
    def __init__(
        self, search_space: dict[str, BaseDistribution] | None = None, independent_sampler: BaseSampler = RandomSampler()
    ) -> None:
```

**Comment by toshihikoyanase** [comment]
Thanks for sharing your idea. I guess the `seed` argument in this PR seems to be a bit simple for users.
As can be seen in the following user code, `MySampler(seed=1)` seems more straightforward for novice users.

```python
## This PR
sampler = MySampler(seed=1)

# Your previous comment
sampler = MySampler(independent_sampler=optuna.samplers.RandomSampler(seed=1))
```

**Comment by y0z** [comment]
@toshihikoyanase 

Thank you for your feedback. I understand the simpler one is better.
If you do not have any other concerns, please approve this PR.

**Review by toshihikoyanase — APPROVED** [review]
LGTM!
Thank you.

**Pull request merged**
